### PR TITLE
Feature/list element with pictures

### PR DESCRIPTION
**Pull request by pjakubczyk**

### CODE REVIEW

**Comment by pjakubczyk** [comment]
@whiter13 run and check :)

**Comment by jbialkowski13** [comment]
@pjakubczyk I observed weird behaviour with Agenda. After first run both days loaded sessions and displayed them, But after exiting the app and reentering it sometimes one of the days does not load content.

**Comment by jbialkowski13** [comment]
@pjakubczyk Should we load data in activity and then deliver them to fragments? 

I have no experience with RoboSpice, I tried it just once so far.

**Comment by pjakubczyk** [comment]
True story bro. RoboSpice uses cache for http requests. I changed the flag to query each time fragment loads.

**Comment by jbialkowski13** [comment]
@pjakubczyk Unfortunately it still happens after your last commit. You can watch it on yt: 
https://youtu.be/gzzR3iB4x-8

**Comment by jbialkowski13** [comment]
Anyway I will merge it to continue with other tasks

**Comment by pjakubczyk** [comment]
Fixed in Master

**Pull request merged**
